Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,15 +11,15 @@ permissions:
 jobs:
 
   # =====================================================
-  # JOB 1 - TERRAFORM INIT & VALIDATE
+  # STAGE 1 - VALIDATE + PLAN
   # =====================================================
-  terraform-validate:
-    name: Terraform Init & Validate
+  terraform-plan:
+    name: Terraform Validate & Plan
     runs-on: self-hosted
 
     defaults:
       run:
-        working-directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev
+        working-directory: Enviroments/dev
 
     steps:
 
@@ -40,37 +40,6 @@ jobs:
       - name: Terraform Validate
         run: terraform validate
 
-
-  # =====================================================
-  # JOB 2 - TERRAFORM PLAN
-  # =====================================================
-  terraform-plan:
-    name: Terraform Plan
-    runs-on: self-hosted
-
-    needs:
-      - terraform-validate
-
-    defaults:
-      run:
-        working-directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev
-
-    steps:
-
-      - name: Checkout Code
-        uses: actions/checkout@v4
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-
-      - name: Azure Login
-        uses: azure/login@v2
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
-
-      - name: Terraform Init
-        run: terraform init
-
       - name: Terraform Plan
         run: terraform plan -out=tfplan
 
@@ -79,21 +48,21 @@ jobs:
         with:
           name: terraform-plan
           path: Enviroments/dev/tfplan
+          if-no-files-found: error
 
 
   # =====================================================
-  # JOB 3 - TERRAFORM APPLY
+  # STAGE 2 - APPLY
   # =====================================================
   terraform-apply:
     name: Terraform Apply
     runs-on: self-hosted
 
-    needs:
-      - terraform-plan
+    needs: terraform-plan
 
     defaults:
       run:
-        working-directory: C:\Agent\actions-runner\_work\terraform-azure-github-actions\terraform-azure-github-actions\Enviroments\dev
+        working-directory: Enviroments/dev
 
     steps:
 
@@ -116,6 +85,20 @@ jobs:
         with:
           name: terraform-plan
           path: Enviroments/dev
+
+      - name: Verify Terraform Plan
+        shell: powershell
+        run: |
+          Write-Host "Current Directory:"
+          Get-Location
+
+          Write-Host "Files:"
+          Get-ChildItem
+
+          if (-not (Test-Path tfplan)) {
+            Write-Error "tfplan file not found!"
+            exit 1
+          }
 
       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
